### ISSUE TITLE
Marshalling issue when requesting tenant statistics

### ISSUE THREAD

**Issue by k-butz** [reubenmiller/go-c8y-cli#204]
The command `c8y tenantstatistics listSummaryAllTenants --dateFrom -1d` leads to an Exception:
```
$ c8y tenantstatistics listSummaryAllTenants --dateFrom -1d
serverError: json: cannot unmarshal array into Go value of type map[string]interface {} json: cannot unmarshal array into Go value of type map[string]interface {}
```

The curl reveals this endpoint seems to be returning an array instead of a map (could be the reason here):
```
curl -H "$C8Y_HEADER" $C8Y_HOST/tenant/statistics/allTenantsSummary
[...]
```

**Comment by reubenmiller** [comment]
Thanks @ButKor for issue. Sorry about that, it is definitely a bug, though it should be an easy fix.
