### ISSUE TITLE
Support Inventory Queries for childAdditions

### ISSUE THREAD

**Issue by k-butz** [reubenmiller/go-c8y-cli#215]
Cumulocity supports to apply an Inventory Query to the `inventory/managedObjects/<id>/childAdditions` endpoint via the `query` parameter. See the docs here: https://cumulocity.com/api/core/10.15.0/#operation/getManagedObjectChildAdditionsResource.

E.g. this call returns all childAdditions of Managed Object 161696403 of type 'myType' and myFragment equals 'hello world':

```
-> c8y api GET "/inventory/managedObjects/161696403/childAdditions?query=\$filter=(type eq myType and myFragment eq 'hello world')" | jq
{
  "managedObject": {
    "additionParents": {
      "references": [],
      "self": "https://t570403874.eu-latest.cumulocity.com/inventory/managedObjects/161696404/additionParents"
    },
    "assetParents": {
      "references": [],
      "self": "https://t570403874.eu-latest.cumulocity.com/inventory/managedObjects/161696404/assetParents"
    },
    "childAdditions": {
      "references": [],
      "self": "https://t570403874.eu-latest.cumulocity.com/inventory/managedObjects/161696404/childAdditions"
    },
    "childAssets": {
      "references": [],
      "self": "https://t570403874.eu-latest.cumulocity.com/inventory/managedObjects/161696404/childAssets"
    },
    "childDevices": {
      "references": [],
      "self": "https://t570403874.eu-latest.cumulocity.com/inventory/managedObjects/161696404/childDevices"
    },
    "creationTime": "2023-02-04T19:35:21.965Z",
    "deviceParents": {
      "references": [],
      "self": "https://t570403874.eu-latest.cumulocity.com/inventory/managedObjects/161696404/deviceParents"
    },
    "id": "161696404",
    "lastUpdated": "2023-02-04T19:35:22.043Z",
    "myFragment": "hello world",
    "owner": "korbinian.butz@softwareag.com",
    "self": "https://t570403874.eu-latest.cumulocity.com/inventory/managedObjects/161696404",
    "type": "myType"
  },
  "self": "https://t570403874.eu-latest.cumulocity.com/inventory/managedObjects/161696403/childAdditions/161696404"
}
```

While this is possible via c8y api command it would be benefitial to have this parameter also selectable in the `c8y inventory children` subcommand (maybe c8y inventory children find?).

**Comment by reubenmiller** [comment]
This is actually already support under the `list` subcommand. It supports a `--query` flag.

Granted it does not have the super nice `c8y inventory find` syntax where it includes a c8y query builder, however I hope it is good enough.

**Examples**

You can just change the value for the `--childType` to what every relationship type (e.g. `addition`, `asset`, `device`).

```
c8y inventory children list --id 1234 --query "name eq 'test'" --childType addition --dry

c8y devices children list --id 1234 --query "name eq 'test'" --childType addition --dry
```

**Docs**
* https://goc8ycli.netlify.app/docs/cli/c8y/inventory/children/c8y_inventory_children_list/
* https://goc8ycli.netlify.app/docs/cli/c8y/devices/children/c8y_devices_children_list/

**Comment by k-butz** [comment]
Perfect, that's what I was searching for!
