### ISSUE TITLE
Add Datahub support to go-c8y-cli

### ISSUE THREAD

**Issue by k-butz** [reubenmiller/go-c8y-cli#234]
Cumulocitys [Data Hub](https://cumulocity.com/guides/datahub/datahub-overview/) module allows Users to query Data from a Data Lake via REST. This is done via an (optional) Microservice hosted within a Tenant.

Idea would be to introduce Datahub support into go-c8y-cli via a new subcommand (e.g. `c8y datahub query`) . Open API Spec for Datahub can be found [here](https://cumulocity.com/datahub/api/10.15.0/). Especially the synchronous [High-Performance API ](https://cumulocity.com/datahub/api/10.15.0/#operation/postPerformanceSQLApiResource) looks very interesting for go-c8y-cli.

**Comment by mbay-ODW** [comment]
+1, like the idea.

**Comment by reubenmiller** [comment]
@ButKor Thanks for creating a ticket, much appreciated 👍

**Comment by reubenmiller** [comment]
@ButKor Though I had to tweak the ticket name to refer to the official project name (go-c8y-cli) ;)
