### ISSUE TITLE
Showing cumulocity system version after connecting (set-session)

### ISSUE THREAD

**Issue by PestusAtSAG** [reubenmiller/go-c8y-cli#249]
It would be nice if the user can direclty see which version after connecting is currently installed:

The version can already retrieved by: c8y currenttenant version

```
> set-session

host: your.tenant.de
tenant: t123456
cumulocity version: 1016.0.214
username: you@company.com
```

**Comment by reubenmiller** [comment]
It will be included in the next release, v2.33.0
