### ISSUE TITLE
Option to ignore default query parameter(s)

### ISSUE THREAD

**Issue by namnhatpham** [reubenmiller/go-c8y-cli#251]
There are cases that the request endpoint does not accept query parameters. Therefore, it is necessary to have the option to allow ignorance of the default query parameters when sending requests.

It could have the setting to ignore all parameters or one/some specific ones.

**Comment by reubenmiller** [comment]
There is a new feature that supports this use case. Available >= v2.30.2.

Check out the [documentation](https://goc8ycli.netlify.app/docs/concepts/extensions/api-commands/command-groups/#example-ignoring-or-mapping-the-pagesize-query-parameter-value) on how to use it.
