### ISSUE TITLE
Print feedback for Alarm bulk-update

### ISSUE THREAD

**Issue by k-butz** [reubenmiller/go-c8y-cli#290]
This command does not print anything to stdout in case it succeeded:
```sh
-> c8y alarms updateCollection --dateTo -3d --newStatus CLEARED -f
```

I guess the reason is because the platform does respond with an empty body to this call. However, would be good if go-c8y-cli could give an indication if the call succeded based on the response status code. Something similar to the `✓ Deleted /alarm/alarms => 204 No Content` messages when deleting stuff.

One could argue "if there's no error, you can assume it succeded". But this gets problematic in pipe scenarios such as:
```sh
-> c8y devices list --type xyz | c8y alarms updateCollection --dateTo -3d --newStatus CLEARED -f
```
If this command does not print output, User does not immediately see if 
a) there are simply no devices of xyz and alarm update was never done or 
b) there were devices of x,y,z and updateCollection succeeded.

**Comment by reubenmiller** [comment]
Resolved in [2.37.0](https://github.com/reubenmiller/go-c8y-cli/releases/tag/v2.37.0)
