### ISSUE TITLE
Compressed API Responses

### ISSUE THREAD

**Issue by k-butz** [reubenmiller/go-c8y-cli#297]
The Cumulocity API is supporting gzip compression - I think go-c8y-cli does not support that yet (at least I did not see the `Accept-Encoding: gzip` header in the requests sent by CLI). 

Should this be supported? If yes, by default or opt-in feature via configuration?

**Comment by reubenmiller** [comment]
This has been included since [2.38.0](https://github.com/reubenmiller/go-c8y-cli/releases/tag/v2.38.0).

Compressed message are enabled by default and it occurs transparently to the user.
