### ISSUE TITLE
Password Issue  in  session create

### ISSUE THREAD

**Issue by kreinhar** [reubenmiller/go-c8y-cli#315]
Hi Gyus

tried to use this  `xx'xxxxxxx+x#"~` as password with set session

`c8y sessions create --type dev --host "https://xxxxx.emea.cumulocity.com/" --username xxxxx --password xx'xxxx+x#"~`

resulted in another missing value

**Comment by k-butz** [comment]
Problem should be that the shell interpretes the single quote of your password as "beginning of a string", it needs to be escaped. In powershell it's escaped using double-single quotes (see this [stackoverflow](https://stackoverflow.com/questions/11231410/can-i-use-a-single-quote-in-a-powershell-string) question).

Try: ` c8y sessions create --type dev --host "https://xxxxx.emea.cumulocity.com/" --username xxxxx --password 'xx''xxxxx+x#"~'`

**Comment by reubenmiller** [comment]
Or an easier solution would be to not specify the `--password xxx` flag and you will be prompted for your password, that way you don't need to worry about shell escaping.
