### ISSUE TITLE
Unable to use any c8y session after creating an encrypted session

### ISSUE THREAD

**Issue by Deepthi-123** [reubenmiller/go-c8y-cli#392]
After creating c8y session with --encrypt option, attempting to set session gives a _commandError: decryption failed_ error message

Steps to Reproduce:
1. Create a c8y session using: `c8y sessions create --host "<HOST>" --username <USERNAME> --password <PASSWORD> --encrypt`
2. Set any session with `set-session`

Expected Output:
All created sessions are listed.

Actual Output:
Setting session fails as below:
`2024-06-13T10:11:18.179+0200    ERROR   commandError: decryption failed
Set session failed`

**Comment by reubenmiller** [comment]
Yes it seems that the encrypted sessions feature broke sometime between 2.39.x and 2.42.1.

I've narrowed down the problem to a degree, but it still need a bit more work before I have a fix (within a week though).

Unfortunately the system tests around setting sessions is proving hard to automate for various reasons...but it is showing the need to have some kind of coverage to prevent these breakages in the future.

**Comment by reubenmiller** [comment]
@Deepthi-123  Ok, I think I've sorted out the issue now (there were a few things causing some problems).

To prevent another failed release, would you be able install the version from the main branch and test it to see if it works as expected?

```sh
go install github.com/reubenmiller/go-c8y-cli/v2/cmd/c8y@b2a98a71920e346accc84fcf1fe4f98e2ab88b19
export PATH="$(go env GOPATH)/bin:$PATH"
```

**Comment by Deepthi-123** [comment]
It works now. Thanks for the fix!

**Comment by reubenmiller** [comment]
The fix is included in the latest release https://github.com/reubenmiller/go-c8y-cli/releases/tag/v2.43.0
