### ISSUE TITLE
createBinary  deadline exeeded

### ISSUE THREAD

**Issue by mstoffel-sag** [reubenmiller/go-c8y-cli#402]
When I try to upload microservice i get the following error:

c8y microservices createBinary --file target/dynamic-mapping-service.zip --id dynamic-mapping-service
? Confirm (job: 1)
Create microservice binary on tenant t15264971
[y] Yes  [a] Yes to All  [n] No  [l] No to All y
elapsed 00:59   dynamic-mapping-service.zip  [━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ] 97 %  207.53 MiB / 213.73 MiB
2024-07-04T10:39:39.716+0200    ERROR   request timed out after 1m0s
2024-07-04T10:39:39.719+0200    ERROR   commandError: command timed out context deadline exceeded

Uploading using the ui works

Version  2.43.0 Platform macos arm64

**Comment by reubenmiller** [comment]
Just use the “—timeout 10m” global flag to increase the timeout (you can also change this globally in your session settings)

Here are the docs about the [default timeout setting](https://goc8ycli.netlify.app/docs/concepts/common-parameters/#timeout)

**Comment by reubenmiller** [comment]
In [v2.43.1](https://github.com/reubenmiller/go-c8y-cli/releases/tag/v2.43.1), the default global request timeout is now 600s
