### ISSUE TITLE
JSON with keys that differ only in case fail to parse into PowerShell objects

### ISSUE THREAD

**Issue by bartoszjanus-cumulocity** [reubenmiller/go-c8y-cli#45]
Hi!

There's one tenant on one of our environments that refuses to parse into an object, because of it getting all tenants at once fails - I just keep getting raw JSON.

With `-PageSize` it just kept giving me raw JSON, but with `-IncludeAll` I got a warning:
```
WARNING: Could not decode json text. Cannot convert the JSON string because it contains keys with different casing. Please use the -AsHashTable switch instead. The key that was attempted to be added to the existing key 'requiredRoles' was 'requiredroles'.
```

There's an application on that tenant with both `requiredRoles` and `requiredroles` keys:
```
            {
                "application": {
                    "availability": "MARKET",
                    "contextPath": "<snip>",
                    "id": "<snip>",
                    "key": "<snip>",
                    "manifest": {
                        "billingMode": "RESOURCES",
                        "noAppSwitcher": true,
                        "settingsCategory": null
                    },
                    "name": "<snip>",
                    "owner": {
                        "self": "<snip>",
                        "tenant": {
                            "id": "<snip>"
                        }
                    },
                    "requiredRoles": [
                        "ROLE_INVENTORY_READ",
                        "ROLE_INVENTORY_CREATE",
                        "ROLE_INVENTORY_ADMIN"
                    ],
                    "requiredroles": [
                        "ROLE_INVENTORY_READ",
                        "ROLE_INVENTORY_CREATE",
                        "ROLE_INVENTORY_ADMIN"
                    ],
                    "roles": [],
                    "self": "<snip>",
                    "type": "MICROSERVICE"
                },
                "self": "<snip>"
            },
```

PowerShell case-insensitivity shenanigans?

**Comment by reubenmiller** [comment]
Yes PSc8y converts the rest response to PowerShell PSObjects where they do not allow duplicate keys (based on case-insensitive matches).

Currently there is not an inbuilt way to use the "-AsHashtable" as it is not exposed to the user. However can call the underlying c8y go binary yourself. The output of the go binary is just text, so you will have to call ConvertFrom-Json yourself (where you can use the appropriate options)

```powershell
$c8y  = Get-ClientBinary
$allTenants = & $c8y tenants list --includeAll | ConvertFrom-Json -AsHashtable
```

Note: Since you are now working with PowerShell hashtables, you will lose the nice "views" and ability to use cmdlts such as `Select-Object`.

But the problem is caused by the incorrect use of the `requiredroles` key, so ideally this should be found and corrected if possible.

**Comment by reubenmiller** [comment]
Also you can see the underlying c8y go binary call by adding `-Verbose` to your cmdlet call that you want. The call should be one of the very first messages.

```powershell
Get-TenantCollection -Verbose -IncludeAll
```

```text
VERBOSE: C:\Users\xxxxxx\Modules\PSc8y\1.11.1\Dependencies\c8y.windows.exe devices list --pretty=false --verbose --noColor --raw
````

**Comment by reubenmiller** [comment]
Here is the PowerShell bug ticket related to ConvertFrom-Json and duplicate keys
https://github.com/PowerShell/PowerShell/issues/14143

**Comment by bartoszjanus-cumulocity** [comment]
Thanks for explaining! I will try to correct the application, for now the workaround is acceptable :)
