### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by EricSand** [reubenmiller/go-c8y-cli#57]
In the [shell installation section](https://goc8ycli.netlify.app/docs/installation/shell-installation/#getting-started) is a dead link to the getting started page.
![image](https://user-images.githubusercontent.com/51123902/129339998-e54395cc-2841-49f2-b83e-bed566729cdd.png)

Currently links to: https://goc8ycli.netlify.app/docs/installation/gettingstarted
Should link to: https://goc8ycli.netlify.app/docs/gettingstarted

**Comment by reubenmiller** [comment]
@EricSand yeah there seems to a problem with how the links are built. If you start at the base page, then navigate to the getting started, then the link works. However if you start on another documentation page, then the links are built incorrectly. It seems to be a general problem with links and not just the link that you posted there.

I'll have to check the docusaurus configuration settings to see if I can fix this.

**Comment by reubenmiller** [comment]
@EricSand Broken relative links (due to trailing slashes) is now fixed and deployed
