### ISSUE TITLE
Enhance shell profile instructions for Homebrew install

### ISSUE THREAD

**Issue by EricSand** [reubenmiller/go-c8y-cli#58]
For MacOS, installation is recommended via Homebrew: [Link](https://goc8ycli.netlify.app/docs/installation/shell-installation#macoslinux-homebrew)

However, in the [shell profile section](https://goc8ycli.netlify.app/docs/installation/shell-installation/#setting-up-your-shell-profile), the correct path is not mentioned leading to some possible frustration ;-)

Therefore, I request to add the correct path for Homebrew installations to the section mentioned above:
`source "/usr/local/etc/go-c8y-cli/shell/c8y.plugin.zsh"`

**Comment by reubenmiller** [comment]
@EricSand Though aren't there printed instructions on the console after installing is via brew?

**Comment by EricSand** [comment]
Yes, but I haven't read them (dont think that they are displayed at install time, I had to use `grew info`), instead following the instruction on the getting started guide. Maybe Im an outlier, but it cannot hurt to include it imho  ;-)

**Comment by reubenmiller** [comment]
@EricSand Yeah I think the instructions are only shown in brew when you install it for the first time (not during upgrades). But I added some brew specific instructions to the [docs](https://goc8ycli.netlify.app/docs/installation/shell-installation/#macoslinux-homebrew)

I also added links to setting up your shell profile in the other installation method sections so it is more obvious that they have to do something manually to their shell profile of choice.

**Comment by reubenmiller** [comment]
Though I just did an upgrade using homebrew (for linux) and the instructions are displayed on the console (under Caveats section), though it is a lot of text...

```sh
==> Upgrading reubenmiller/go-c8y-cli/go-c8y-cli
  2.1.1 -> 2.1.2

==> Downloading https://github.com/reubenmiller/go-c8y-cli/releases/download/v2.1.2/c8y_2.1.2_linux_amd64.tar.gz
==> Downloading from https://github-releases.githubusercontent.com/260410471/b4c90b0c-8260-45d4-a02d-ed083d413907?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Cre
######################################################################## 100.0%
==> git -C /home/linuxbrew/.linuxbrew/etc/go-c8y-cli pull --ff-only
==> Caveats
Please add the following to your shell profile to enable usage of "set-session" and other helpful c8y utility functions

bash: ~/.bashrc

  source "/home/linuxbrew/.linuxbrew/etc/go-c8y-cli/shell/c8y.plugin.sh"

zsh: ~/.zshrc

  source "/home/linuxbrew/.linuxbrew/etc/go-c8y-cli/shell/c8y.plugin.zsh"

fish: ~/.config/fish/config.fish

  source "/home/linuxbrew/.linuxbrew/etc/go-c8y-cli/shell/c8y.plugin.fish"

powershell: ~/.config/powershell/Microsoft.PowerShell_profile.ps1
  . "/home/linuxbrew/.linuxbrew/etc/go-c8y-cli/shell/c8y.plugin.ps1"

You will also need to force reload of your profile:

  source <profile>

zsh completions have been installed to:
  /home/linuxbrew/.linuxbrew/share/zsh/site-functions
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/go-c8y-cli/2.1.2: 261 files, 18.5MB, built in 2 seconds
Removing: /home/linuxbrew/.linuxbrew/Cellar/go-c8y-cli/2.1.1... (261 files, 18.5MB)
Removing: /home/reubenmiller/.cache/Homebrew/go-c8y-cli--2.1.1.tar.gz... (5.3MB)
```
